#!/bin/bash
# AI generated
## Description: Run PHPCS on custom code using phpcs.xml.dist.
## Usage: phpcs [path...]
## Example: "ddev phpcs" (scans web/modules/custom + web/themes/custom) or "ddev phpcs web/modules/custom/doesdesign_tools"

cd /var/www/html
if [ -z "$*" ]; then
  bin/phpcs --standard=phpcs.xml.dist
else
  bin/phpcs --standard=phpcs.xml.dist --colors "$@"
fi
