#!/bin/bash
# AI generated
## Description: Run PHPCBF to automatically fix code style issues, using phpcs.xml.dist.
## Usage: phpcbf [path...]
## Example: "ddev phpcbf" (fixes web/modules/custom + web/themes/custom) or "ddev phpcbf web/modules/custom/doesdesign_tools"

cd /var/www/html
if [ -z "$*" ]; then
  bin/phpcbf --standard=phpcs.xml.dist
else
  bin/phpcbf --standard=phpcs.xml.dist "$@"
fi
